import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { EmptyState, Pill, ScreenTitle } from "@/components/university-ui";
import { ScreenContainer } from "@/components/screen-container";
import { getCourse } from "@/lib/university";
import { useUniversity } from "@/lib/university-context";

export default function CertificatesScreen() {
  const { certificates } = useUniversity();
  return <ScreenContainer className="px-5" safeAreaClassName="pt-2"><FlatList data={certificates} keyExtractor={(item) => item.id} renderItem={({ item }) => { const course = getCourse(item.courseId); return <Pressable onPress={() => router.push(`/verify/${item.id}` as never)} style={({ pressed }) => [styles.card, pressed && { opacity: 0.75 }]}><View style={styles.banner}><View style={styles.seal}><MaterialIcons name="workspace-premium" size={25} color="#D6A84B" /></View><Text style={styles.bannerLabel}>ONLINE UNIVERSITY</Text><Text style={styles.bannerTitle}>Certificate of completion</Text></View><View style={styles.body}><Pill label="Verified" tone="green" /><Text style={styles.course}>{course.title}</Text><Text style={styles.awarded}>Awarded to {item.learnerName}</Text><View style={styles.footer}><Text style={styles.certificateId}>{item.id}</Text><View style={styles.score}><MaterialIcons name="grade" size={16} color="#9A6F1E" /><Text style={styles.scoreText}>{item.finalScore}% final score</Text></View></View></View></Pressable>; }} ListHeaderComponent={<><ScreenTitle eyebrow="Achievement record" title="Certificates" /><View style={styles.info}><MaterialIcons name="verified-user" size={20} color="#177648" /><Text style={styles.infoText}>Your certificates include a verification ID and final score.</Text></View></>} ListEmptyComponent={<EmptyState icon="workspace-premium" title="Certificates appear here" message="Complete an eligible course and pass the final assessment to receive your certificate." />} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingBottom: 20 }, info: { flexDirection: "row", alignItems: "center", gap: 9, backgroundColor: "#EAF5EF", padding: 12, borderRadius: 14, marginBottom: 16 }, infoText: { color: "#286245", fontSize: 12, flex: 1, lineHeight: 17 }, card: { backgroundColor: "#FFFFFF", borderRadius: 18, borderWidth: 1, borderColor: "#E3EAF0", overflow: "hidden", marginBottom: 14 }, banner: { backgroundColor: "#102A43", alignItems: "center", paddingVertical: 21, paddingHorizontal: 18 }, seal: { width: 43, height: 43, borderRadius: 22, borderWidth: 1, borderColor: "#D6A84B80", alignItems: "center", justifyContent: "center", marginBottom: 9 }, bannerLabel: { color: "#D6A84B", fontSize: 10, fontWeight: "800", letterSpacing: 1.2 }, bannerTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "800", marginTop: 4 }, body: { padding: 15 }, course: { color: "#102A43", fontSize: 17, fontWeight: "800", marginTop: 9, lineHeight: 22 }, awarded: { color: "#627D98", fontSize: 13, marginTop: 4 }, footer: { borderTopWidth: 1, borderTopColor: "#E8EEF2", marginTop: 14, paddingTop: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, certificateId: { color: "#4A5E73", fontSize: 11, fontWeight: "800" }, score: { flexDirection: "row", gap: 4, alignItems: "center" }, scoreText: { color: "#9A6F1E", fontSize: 11, fontWeight: "800" } });
