import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { CourseCard } from "@/components/course-card";
import { Metric, Pill, ProgressBar, ScreenTitle, SectionHeader } from "@/components/university-ui";
import { ScreenContainer } from "@/components/screen-container";
import { getCourse, universityCourses } from "@/lib/university";
import { useUniversity } from "@/lib/university-context";

export default function HomeScreen() {
  const { enrolledIds, progress, certificates } = useUniversity();
  const continuing = getCourse(enrolledIds[0]);
  const continuingProgress = progress[continuing.id] ?? 0;
  const recommendations = universityCourses.filter((course) => !enrolledIds.includes(course.id) && course.status === "Published").slice(0, 2);
  return <ScreenContainer className="px-5" safeAreaClassName="pt-2"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><ScreenTitle eyebrow="Monday, 24 August" title="Good morning, Jordan" right={<Pressable onPress={() => router.push("/profile")} style={({ pressed }) => [styles.avatar, pressed && { opacity: 0.7 }]}><Text style={styles.avatarText}>JT</Text></Pressable>} /><Pressable onPress={() => router.push(`/learn/${continuing.id}/${continuing.modules[1]?.lessons[0]?.id ?? continuing.modules[0].lessons[0].id}` as never)} style={({ pressed }) => [styles.hero, pressed && { opacity: 0.85 }]}><View style={styles.heroTop}><View><Text style={styles.heroEyebrow}>CONTINUE LEARNING</Text><Text style={styles.heroTitle}>{continuing.shortTitle}</Text></View><View style={styles.playCircle}><MaterialIcons name="play-arrow" size={25} color="#102A43" /></View></View><Text style={styles.heroLesson}>Next: {continuing.modules[1]?.lessons[0]?.title ?? continuing.modules[0].lessons[0].title}</Text><ProgressBar progress={continuingProgress} color="#D6A84B" label="Your progress" /></Pressable><View style={styles.metrics}><Metric icon="menu-book" value={String(enrolledIds.length)} label="Active courses" /><Metric icon="bolt" value="3" label="Week streak" tone="#9A6F1E" /><Metric icon="workspace-premium" value={String(certificates.length)} label="Certificates" tone="#177648" /></View><View style={styles.sectionSpace}><SectionHeader title="Recommended for you" action="Discover" /></View>{recommendations.map((course) => <CourseCard key={course.id} course={course} />)}<View style={styles.sectionSpace}><SectionHeader title="Academic progress" /></View><View style={styles.progressCard}><View style={styles.progressHead}><View><Text style={styles.progressTitle}>On a steady path</Text><Text style={styles.progressText}>You have completed 4 learning activities this week.</Text></View><Pill label="+12%" tone="green" /></View><View style={styles.progressRow}><View style={styles.progressDot} /><Text style={styles.progressItem}>Module 2 assessment due in 3 days</Text><MaterialIcons name="chevron-right" size={20} color="#829AB1" /></View></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingBottom: 23 }, avatar: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#102A43", alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, hero: { backgroundColor: "#102A43", borderRadius: 20, padding: 18, marginBottom: 16 }, heroTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, heroEyebrow: { color: "#D6A84B", fontWeight: "800", fontSize: 10, letterSpacing: 1.2 }, heroTitle: { color: "#FFFFFF", fontSize: 22, lineHeight: 28, fontWeight: "800", maxWidth: 230, marginTop: 6 }, playCircle: { width: 43, height: 43, backgroundColor: "#D6A84B", borderRadius: 15, alignItems: "center", justifyContent: "center" }, heroLesson: { color: "#CEDCE8", fontSize: 13, marginTop: 19, marginBottom: 13 }, metrics: { flexDirection: "row", justifyContent: "space-between" }, sectionSpace: { marginTop: 25 }, progressCard: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E3EAF0", borderRadius: 18, padding: 15 }, progressHead: { flexDirection: "row", justifyContent: "space-between", gap: 14 }, progressTitle: { color: "#102A43", fontSize: 16, fontWeight: "800" }, progressText: { color: "#627D98", fontSize: 12, lineHeight: 17, marginTop: 4, maxWidth: 220 }, progressRow: { flexDirection: "row", alignItems: "center", marginTop: 14, paddingTop: 13, borderTopWidth: 1, borderTopColor: "#E8EEF2", gap: 8 }, progressDot: { width: 8, height: 8, backgroundColor: "#D6A84B", borderRadius: 4 }, progressItem: { flex: 1, color: "#4A5E73", fontSize: 12, fontWeight: "600" } });
