import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { Metric, ScreenTitle } from "@/components/university-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { useUniversity } from "@/lib/university-context";

export default function ProfileScreen() {
  const { enrolledIds, certificates } = useUniversity();
  const { isAuthenticated, loading, user } = useAuth();
  if (loading) return <ScreenContainer className="items-center justify-center"><Text className="text-muted">Loading account…</Text></ScreenContainer>;
  if (!isAuthenticated) return <ScreenContainer className="px-5" safeAreaClassName="pt-2"><ScrollView contentContainerStyle={styles.content}><ScreenTitle eyebrow="Account access" title="Sign in to continue" /><View style={styles.signInCard}><View style={styles.signInIcon}><MaterialIcons name="lock-outline" size={28} color="#D6A84B" /></View><Text style={styles.signInTitle}>Your learning record is protected</Text><Text style={styles.signInText}>Sign in with your Online University account to access enrolments, purchases, and certificates securely.</Text><Pressable onPress={() => router.push("/login" as never)} style={styles.signInButton}><Text style={styles.signInButtonText}>Sign in or create account</Text></Pressable></View></ScrollView></ScreenContainer>;
  const displayName = user?.name || "Learner";
  const initials = displayName.split(" ").map((value) => value[0]).slice(0, 2).join("").toUpperCase();
  const canAuthor = user?.role === "admin" || user?.role === "instructor";
  const isAdmin = user?.role === "admin";
  return <ScreenContainer className="px-5" safeAreaClassName="pt-2"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><ScreenTitle eyebrow="Learner profile" title={displayName} right={<View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View>} /><View style={styles.identity}><View><Text style={styles.email}>{user?.email || "Signed-in learner"}</Text><Text style={styles.member}>{isAdmin ? "Online University administrator" : user?.role === "instructor" ? "Online University instructor" : "Online University learner"}</Text></View><View style={styles.verified}><MaterialIcons name="verified" size={17} color="#177648" /><Text style={styles.verifiedText}>Secure session</Text></View></View><View style={styles.metrics}><Metric icon="menu-book" value={String(enrolledIds.length)} label="Active courses" /><Metric icon="workspace-premium" value={String(certificates.length)} label="Certificates" tone="#9A6F1E" /><Metric icon="timeline" value="68%" label="Learning pace" tone="#177648" /></View>{canAuthor ? <><Text style={styles.sectionTitle}>Authoring</Text><WorkspaceCard icon="edit-note" title="Open production course studio" body="Create server-backed courses, rich lessons, and hosted video." onPress={() => router.push("/admin/production" as never)} /></> : null}{isAdmin ? <><Text style={styles.sectionTitle}>Administration</Text><WorkspaceCard icon="admin-panel-settings" title="Manage university operations" body="Manage learners, course visibility, and verified credentials." onPress={() => router.push("/admin/manage" as never)} /></> : null}<Text style={styles.sectionTitle}>Account</Text>{[["Notifications", "notifications-none"], ["Learning preferences", "tune"], ["Privacy & security", "shield-outlined"]].map(([label, icon]) => <View style={styles.setting} key={label}><MaterialIcons name={icon as never} size={21} color="#183B65" /><Text style={styles.settingText}>{label}</Text><MaterialIcons name="chevron-right" size={21} color="#829AB1" /></View>)}</ScrollView></ScreenContainer>;
}

function WorkspaceCard({ icon, title, body, onPress }: { icon: string; title: string; body: string; onPress: () => void }) {
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.adminCard, pressed && { opacity: 0.75 }]}><View style={styles.adminIcon}><MaterialIcons name={icon as never} size={21} color="#D6A84B" /></View><View style={{ flex: 1 }}><Text style={styles.adminTitle}>{title}</Text><Text style={styles.adminText}>{body}</Text></View><MaterialIcons name="chevron-right" size={23} color="#FFFFFF" /></Pressable>;
}

const styles = StyleSheet.create({ content: { paddingBottom: 25 }, avatar: { width: 44, height: 44, borderRadius: 15, backgroundColor: "#102A43", alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" }, identity: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "#FFFFFF", borderRadius: 16, padding: 14, borderWidth: 1, borderColor: "#E3EAF0" }, email: { color: "#102A43", fontSize: 14, fontWeight: "700" }, member: { color: "#627D98", fontSize: 12, marginTop: 3 }, verified: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: "#EAF5EF", paddingVertical: 6, paddingHorizontal: 8, borderRadius: 10 }, verifiedText: { color: "#177648", fontWeight: "800", fontSize: 11 }, metrics: { flexDirection: "row", justifyContent: "space-between", marginTop: 16 }, sectionTitle: { color: "#102A43", fontSize: 16, fontWeight: "800", marginTop: 24, marginBottom: 10 }, adminCard: { backgroundColor: "#102A43", padding: 15, borderRadius: 17, flexDirection: "row", alignItems: "center", gap: 12 }, adminIcon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF18" }, adminTitle: { color: "#FFFFFF", fontWeight: "800", fontSize: 14 }, adminText: { color: "#D2DFEA", fontSize: 12, lineHeight: 17, marginTop: 3 }, setting: { flexDirection: "row", alignItems: "center", backgroundColor: "#FFFFFF", padding: 15, borderRadius: 14, borderWidth: 1, borderColor: "#E3EAF0", marginBottom: 8, gap: 12 }, settingText: { color: "#102A43", fontSize: 14, fontWeight: "700", flex: 1 }, signInCard: { backgroundColor: "#FFFFFF", borderRadius: 19, borderWidth: 1, borderColor: "#E3EAF0", padding: 22, alignItems: "center" }, signInIcon: { width: 58, height: 58, borderRadius: 20, backgroundColor: "#102A43", alignItems: "center", justifyContent: "center" }, signInTitle: { color: "#102A43", fontSize: 18, fontWeight: "800", marginTop: 14 }, signInText: { color: "#627D98", fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 6 }, signInButton: { backgroundColor: "#D6A84B", borderRadius: 12, paddingVertical: 13, paddingHorizontal: 16, marginTop: 18 }, signInButtonText: { color: "#102A43", fontSize: 13, fontWeight: "800" } });
